
---
- hosts: all
  become: yes
  roles:
  - jdk
  - maven
  - myjenkins
  ##- swap
  - sonarqube_latest
  - nexus
  - tomcat
  - sqlinstall
  - { role: jdk,tags: java }
  - { role: maven,tags: maven }
  - { role: myjenkins,tags: jenkins }
  - { role: swap,tags: swapmem }
  - { role: sonarqube_latest,tags: sonar }
  - { role: nexus,tags: nexus }
  - { role: tomcat,tags: tomcat }
  - { role: sqlinstall,tags: mysql }
